"""Remove is_primary column

Revision ID: 00cdc98c45cd
Revises: e40cfdda063f
Create Date: 2026-06-20 19:52:12.572358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cdc98c45cd'
down_revision: Union[str, Sequence[str], None] = 'e40cfdda063f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
