"""Add extra_file_id

Revision ID: 4dbc5e8f480e
Revises: 00cdc98c45cd
Create Date: 2026-06-21 01:01:23.214653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbc5e8f480e'
down_revision: Union[str, Sequence[str], None] = '00cdc98c45cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'scraper_logs' not in tables:
        op.create_table('scraper_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('task_id', sa.Integer(), nullable=True),
        sa.Column('media_item_id', sa.Integer(), nullable=True),
        sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
        sa.Column('search_query', sa.String(), nullable=False),
        sa.Column('result_count', sa.Integer(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['task_id'], ['background_tasks.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('scraper_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_scraper_logs_media_item_id'), ['media_item_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_scraper_logs_provider'), ['provider'], unique=False)
            batch_op.create_index(batch_op.f('ix_scraper_logs_search_query'), ['search_query'], unique=False)
            batch_op.create_index(batch_op.f('ix_scraper_logs_task_id'), ['task_id'], unique=False)

    action_logs_cols = [c['name'] for c in inspector.get_columns('action_logs')]
    if 'extra_file_id' not in action_logs_cols:
        with op.batch_alter_table('action_logs', schema=None) as batch_op:
            batch_op.add_column(sa.Column('extra_file_id', sa.Integer(), nullable=True))
            batch_op.create_index(batch_op.f('ix_action_logs_extra_file_id'), ['extra_file_id'], unique=False)
            batch_op.create_foreign_key('fk_action_logs_extra_file_id_extra_files', 'extra_files', ['extra_file_id'], ['id'], ondelete='SET NULL')

    background_tasks_cols = [c['name'] for c in inspector.get_columns('background_tasks')]
    if 'error_code' not in background_tasks_cols:
        with op.batch_alter_table('background_tasks', schema=None) as batch_op:
            batch_op.add_column(sa.Column('error_code', sa.Enum('RATE_LIMIT', 'API_KEY_MISSING', 'NETWORK_ERROR', 'DATABASE_LOCK', 'NO_MATCH', 'UNKNOWN', name='taskerrorcode'), nullable=True))
            batch_op.create_index(batch_op.f('ix_background_tasks_error_code'), ['error_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_error_code'))
        batch_op.drop_column('error_code')

    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_action_logs_extra_file_id_extra_files', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_action_logs_extra_file_id'))
        batch_op.drop_column('extra_file_id')

    with op.batch_alter_table('scraper_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scraper_logs_task_id'))
        batch_op.drop_index(batch_op.f('ix_scraper_logs_search_query'))
        batch_op.drop_index(batch_op.f('ix_scraper_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_scraper_logs_media_item_id'))

    op.drop_table('scraper_logs')
    # ### end Alembic commands ###
