"""Initial schema migration

Revision ID: 6262c9c39e90
Revises: 
Create Date: 2026-06-20 18:44:06.073508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6262c9c39e90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('watch_for_changes', sa.Boolean(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_path')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_is_adult'), ['is_adult'], unique=False)

    op.create_table('media_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_collection_provider')
    )
    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_collections_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_collections_provider'), ['provider'], unique=False)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('deathday', sa.String(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('known_for_department', sa.String(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.Column('local_profile_path', sa.String(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('socials', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('measurements', sa.String(), nullable=True),
    sa.Column('cup_size', sa.String(), nullable=True),
    sa.Column('tattoos', sa.String(), nullable=True),
    sa.Column('piercings', sa.String(), nullable=True),
    sa.Column('orientation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_cup_size'), ['cup_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_ethnicity'), ['ethnicity'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_hair_color'), ['hair_color'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_height'), ['height'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_is_adult'), ['is_adult'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_known_for_department'), ['known_for_department'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_orientation'), ['orientation'], unique=False)

    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('parent_studio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_studio_id'], ['studios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_studios_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_studios_parent_studio_id'), ['parent_studio_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('custom_image_backdrop', sa.String(), nullable=True),
    sa.Column('custom_image_poster_1', sa.String(), nullable=True),
    sa.Column('custom_image_poster_2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_is_adult'), ['is_adult'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_adult', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('action_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_batches_user_id'), ['user_id'], unique=False)

    op.create_table('background_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'ABORTED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_tasks_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('custom_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('list_type', sa.Enum('MEDIA', 'MATCH', 'PERSON', 'STUDIO', 'COLLECTION', name='customlisttype'), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_lists_list_type'), ['list_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_lists_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_lists_user_id'), ['user_id'], unique=False)

    op.create_table('external_collection_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['media_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'provider', 'external_id', name='uq_collection_external_source')
    )
    with op.batch_alter_table('external_collection_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_collection_links_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_collection_links_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_collection_links_provider'), ['provider'], unique=False)

    op.create_table('external_source_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'provider', 'external_id', name='uq_person_external_source')
    )
    with op.batch_alter_table('external_source_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_source_links_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_source_links_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_source_links_provider'), ['provider'], unique=False)

    op.create_table('external_studio_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studio_id', 'provider', 'external_id', name='uq_studio_external_source')
    )
    with op.batch_alter_table('external_studio_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_studio_links_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_studio_links_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_studio_links_studio_id'), ['studio_id'], unique=False)

    op.create_table('media_collection_localizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('local_poster_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['media_collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'locale', name='uq_collection_locale')
    )
    with op.batch_alter_table('media_collection_localizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_collection_localizations_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_collection_localizations_locale'), ['locale'], unique=False)

    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('folder_name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.Float(), nullable=True),
    sa.Column('hash_md5', sa.String(), nullable=True),
    sa.Column('hash_oshash', sa.String(), nullable=True),
    sa.Column('hash_sha256', sa.String(), nullable=True),
    sa.Column('group_hash', sa.String(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('total_parts', sa.Integer(), nullable=True),
    sa.Column('internal_title', sa.String(), nullable=True),
    sa.Column('nfo_imdb_id', sa.String(), nullable=True),
    sa.Column('parsed_info', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('video_codec', sa.String(), nullable=True),
    sa.Column('video_bitrate', sa.Integer(), nullable=True),
    sa.Column('framerate', sa.String(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('hdr_type', sa.String(), nullable=True),
    sa.Column('audio_codec', sa.String(), nullable=True),
    sa.Column('audio_channels', sa.String(), nullable=True),
    sa.Column('audio_bitrate', sa.Integer(), nullable=True),
    sa.Column('audio_streams', sa.JSON(), nullable=True),
    sa.Column('subtitle_streams', sa.JSON(), nullable=True),
    sa.Column('edition', sa.Enum('NONE', 'THEATRICAL', 'DIRECTORS_CUT', 'EXTENDED', 'UNRATED', 'REMASTERED', 'SPECIAL', 'ULTIMATE', 'COLLECTORS_EDITION', 'FAN_EDIT', name='movieedition'), nullable=False),
    sa.Column('audio_type', sa.Enum('NONE', 'MONO', 'STEREO', 'SURROUND', 'DUAL_AUDIO', 'MULTI_AUDIO', name='mediaaudiotype'), nullable=False),
    sa.Column('source', sa.Enum('NONE', 'BLURAY', 'WEB', 'DVD', 'TV', 'CAM', name='mediasource'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'NO_MATCH', 'UNCERTAIN', 'MULTIPLE', 'MATCHED', 'ORGANIZED', 'RENAMED', 'ERROR', 'IGNORED', 'MISSING', name='itemstatus'), nullable=False),
    sa.Column('ignored_previous_status', sa.Enum('NEW', 'NO_MATCH', 'UNCERTAIN', 'MULTIPLE', 'MATCHED', 'ORGANIZED', 'RENAMED', 'ERROR', 'IGNORED', 'MISSING', name='itemstatus'), nullable=True),
    sa.Column('ignored_at', sa.DateTime(), nullable=True),
    sa.Column('planned_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'relative_path', name='uq_library_relative_path')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_audio_type'), ['audio_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_edition'), ['edition'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_folder_name'), ['folder_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_group_hash'), ['group_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_hash_md5'), ['hash_md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_hash_oshash'), ['hash_oshash'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_hash_sha256'), ['hash_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_ignored_at'), ['ignored_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_mtime'), ['mtime'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_size'), ['size'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_status'), ['status'], unique=False)

    op.create_table('person_localizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('biography', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'locale', name='uq_person_locale')
    )
    with op.batch_alter_table('person_localizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_localizations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_localizations_person_id'), ['person_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_key')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=False)

    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.Enum('RENAME', 'MOVE', 'COPY', 'DELETE', 'METADATA_UPDATE', 'IDENTIFY', name='actiontype'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'UNDONE', name='actionstatus'), nullable=False),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['action_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_status'), ['status'], unique=False)

    op.create_table('extra_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('VIDEO', 'IMAGE', 'METADATA', 'SUBTITLE', 'AUDIO', name='extracategory'), nullable=False),
    sa.Column('subtype', sa.Enum('TRAILER', 'SAMPLE', 'BEHIND_THE_SCENES', 'FEATURETTE', 'DELETED_SCENES', 'INTERVIEW', 'SCENE_COMPARISON', 'SHORT', 'PROMO', 'CLIP', 'POSTER', 'FANART', 'DISC', 'BACKDROP', 'BANNER', 'THUMBNAIL', 'LOGO', 'CLEARLOGO', 'CHARACTER_ART', 'FULL', 'FORCED', 'SDH', 'HEARING_IMPAIRED', 'COMMENTARY_SUB', 'LYRICS', 'DUBBED', 'ORIGINAL', 'COMMENTARY_AUDIO', 'DESCRIPTIVE', 'ISOLATED_SCORE', 'NFO', 'XML', 'JSON', 'TXT', 'URL', 'OTHER', name='extrasubtype'), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extra_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extra_files_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_extra_files_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_extra_files_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extra_files_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_extra_files_subtype'), ['subtype'], unique=False)

    op.create_table('metadata_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('MOVIE', 'TV', 'SEASON', 'EPISODE', 'SCENE', 'PERSON', 'VIDEO', 'COLLECTION', name='mediatype'), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.JSON(), nullable=True),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('number_of_episodes', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_tmdb', sa.Float(), nullable=True),
    sa.Column('rating_imdb', sa.Float(), nullable=True),
    sa.Column('rating_rotten', sa.String(), nullable=True),
    sa.Column('rating_meta', sa.Integer(), nullable=True),
    sa.Column('vote_count_tmdb', sa.Integer(), nullable=True),
    sa.Column('vote_count_imdb', sa.Integer(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('release_status', sa.String(), nullable=True),
    sa.Column('tv_type', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('last_air_date', sa.DateTime(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('original_title', sa.String(), nullable=True),
    sa.Column('backdrop_path', sa.String(), nullable=True),
    sa.Column('local_backdrop_path', sa.String(), nullable=True),
    sa.Column('still_path', sa.String(), nullable=True),
    sa.Column('local_still_path', sa.String(), nullable=True),
    sa.Column('suggested_tags', sa.JSON(), nullable=True),
    sa.Column('stills', sa.JSON(), nullable=True),
    sa.Column('local_stills', sa.JSON(), nullable=True),
    sa.Column('fetched_locales', sa.JSON(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['media_collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', 'media_type', name='uq_provider_match')
    )
    with op.batch_alter_table('metadata_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_matches_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_imdb_id'), ['imdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_is_adult'), ['is_adult'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_original_title'), ['original_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_popularity'), ['popularity'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_rating_imdb'), ['rating_imdb'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_matches_release_date'), ['release_date'], unique=False)

    op.create_table('playback_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=False),
    sa.Column('position_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playback_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playback_logs_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_logs_watched_at'), ['watched_at'], unique=False)

    op.create_table('playback_peak_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('video_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playback_peak_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playback_peak_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_peak_logs_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_playback_peak_logs_user_id'), ['user_id'], unique=False)

    op.create_table('custom_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['media_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['custom_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_list_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_studio_id'), ['studio_id'], unique=False)

    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_match_id', sa.Integer(), nullable=False),
    sa.Column('child_match_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['child_match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_match_id', 'child_match_id', 'relation_type', name='uq_entity_relation')
    )
    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_relations_child_match_id'), ['child_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_parent_match_id'), ['parent_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_relation_type'), ['relation_type'], unique=False)

    op.create_table('external_match_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('TMDB', 'OMDB', 'STASHDB', 'PORNDB', 'FANSDB', 'MANUAL', name='provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'provider', 'external_id', name='uq_match_external_source')
    )
    with op.batch_alter_table('external_match_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_match_links_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_match_links_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_match_links_provider'), ['provider'], unique=False)

    op.create_table('media_person_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ACTOR', 'DIRECTOR', 'WRITER', 'PRODUCER', 'CREATOR', name='roletype'), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_person_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_person_links_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_person_links_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_person_links_role'), ['role'], unique=False)

    op.create_table('metadata_localizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('overview', sa.String(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=True),
    sa.Column('local_poster_path', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('local_logo_path', sa.String(), nullable=True),
    sa.Column('trailer_url', sa.String(), nullable=True),
    sa.Column('origin_country', sa.JSON(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('spoken_languages', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'locale', name='uq_match_locale')
    )
    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_localizations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_localizations_match_id'), ['match_id'], unique=False)

    op.create_table('metadata_match_studios',
    sa.Column('metadata_match_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metadata_match_id', 'studio_id')
    )
    with op.batch_alter_table('metadata_match_studios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_match_studios_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_match_studios_studio_id'), ['studio_id'], unique=False)

    op.create_table('user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=True),
    sa.Column('metadata_match_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('custom_title', sa.String(), nullable=True),
    sa.Column('custom_overview', sa.String(), nullable=True),
    sa.Column('custom_poster', sa.String(), nullable=True),
    sa.Column('custom_backdrop', sa.String(), nullable=True),
    sa.Column('custom_logo', sa.String(), nullable=True),
    sa.Column('custom_edition', sa.Enum('NONE', 'THEATRICAL', 'DIRECTORS_CUT', 'EXTENDED', 'UNRATED', 'REMASTERED', 'SPECIAL', 'ULTIMATE', 'COLLECTORS_EDITION', 'FAN_EDIT', name='movieedition'), nullable=True),
    sa.Column('custom_audio_type', sa.Enum('NONE', 'MONO', 'STEREO', 'SURROUND', 'DUAL_AUDIO', 'MULTI_AUDIO', name='mediaaudiotype'), nullable=True),
    sa.Column('custom_source', sa.Enum('NONE', 'BLURAY', 'WEB', 'DVD', 'TV', 'CAM', name='mediasource'), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_rating_at', sa.DateTime(), nullable=True),
    sa.Column('user_comment', sa.String(), nullable=True),
    sa.Column('user_comment_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_favorite_at', sa.DateTime(), nullable=True),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(), nullable=True),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('resume_position', sa.Integer(), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['media_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metadata_match_id'], ['metadata_matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'collection_id', name='uq_user_collection'),
    sa.UniqueConstraint('user_id', 'media_item_id', name='uq_user_media_item'),
    sa.UniqueConstraint('user_id', 'metadata_match_id', name='uq_user_metadata_match'),
    sa.UniqueConstraint('user_id', 'person_id', name='uq_user_person'),
    sa.UniqueConstraint('user_id', 'studio_id', name='uq_user_studio')
    )
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_overrides_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_favorite_at'), ['is_favorite_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_tracked'), ['is_tracked'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_watched'), ['is_watched'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_last_watched_at'), ['last_watched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_comment_at'), ['user_comment_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_rating_at'), ['user_rating_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_watch_count'), ['watch_count'], unique=False)

    op.create_table('user_override_tags',
    sa.Column('user_override_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_override_id'], ['user_overrides.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_override_id', 'tag_id')
    )
    with op.batch_alter_table('user_override_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_override_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_override_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_override_tags_tag_id'))

    op.drop_table('user_override_tags')
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_overrides_watch_count'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_rating_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_comment_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_last_watched_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_watched'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_tracked'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_favorite_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_favorite'))

    op.drop_table('user_overrides')
    with op.batch_alter_table('metadata_match_studios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_match_studios_studio_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_match_studios_relation_type'))

    op.drop_table('metadata_match_studios')
    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_localizations_match_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_localizations_locale'))

    op.drop_table('metadata_localizations')
    with op.batch_alter_table('media_person_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_person_links_role'))
        batch_op.drop_index(batch_op.f('ix_media_person_links_person_id'))
        batch_op.drop_index(batch_op.f('ix_media_person_links_match_id'))

    op.drop_table('media_person_links')
    with op.batch_alter_table('external_match_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_match_links_provider'))
        batch_op.drop_index(batch_op.f('ix_external_match_links_match_id'))
        batch_op.drop_index(batch_op.f('ix_external_match_links_external_id'))

    op.drop_table('external_match_links')
    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_parent_match_id'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_child_match_id'))

    op.drop_table('entity_relations')
    with op.batch_alter_table('custom_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_list_items_studio_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_person_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_order'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_match_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_collection_id'))

    op.drop_table('custom_list_items')
    with op.batch_alter_table('playback_peak_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playback_peak_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_playback_peak_logs_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_playback_peak_logs_created_at'))

    op.drop_table('playback_peak_logs')
    with op.batch_alter_table('playback_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playback_logs_watched_at'))
        batch_op.drop_index(batch_op.f('ix_playback_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_playback_logs_media_item_id'))

    op.drop_table('playback_logs')
    with op.batch_alter_table('metadata_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_matches_release_date'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_rating_imdb'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_provider'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_popularity'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_parent_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_original_title'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_media_type'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_is_adult'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_imdb_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_external_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_matches_collection_id'))

    op.drop_table('metadata_matches')
    with op.batch_alter_table('extra_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extra_files_subtype'))
        batch_op.drop_index(batch_op.f('ix_extra_files_relative_path'))
        batch_op.drop_index(batch_op.f('ix_extra_files_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_extra_files_file_hash'))
        batch_op.drop_index(batch_op.f('ix_extra_files_category'))

    op.drop_table('extra_files')
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_logs_status'))
        batch_op.drop_index(batch_op.f('ix_action_logs_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_batch_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_action_type'))

    op.drop_table('action_logs')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_key'))

    op.drop_table('user_settings')
    with op.batch_alter_table('person_localizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_localizations_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_localizations_locale'))

    op.drop_table('person_localizations')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_status'))
        batch_op.drop_index(batch_op.f('ix_media_items_source'))
        batch_op.drop_index(batch_op.f('ix_media_items_size'))
        batch_op.drop_index(batch_op.f('ix_media_items_relative_path'))
        batch_op.drop_index(batch_op.f('ix_media_items_mtime'))
        batch_op.drop_index(batch_op.f('ix_media_items_library_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_ignored_at'))
        batch_op.drop_index(batch_op.f('ix_media_items_hash_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_items_hash_oshash'))
        batch_op.drop_index(batch_op.f('ix_media_items_hash_md5'))
        batch_op.drop_index(batch_op.f('ix_media_items_group_hash'))
        batch_op.drop_index(batch_op.f('ix_media_items_folder_name'))
        batch_op.drop_index(batch_op.f('ix_media_items_filename'))
        batch_op.drop_index(batch_op.f('ix_media_items_edition'))
        batch_op.drop_index(batch_op.f('ix_media_items_audio_type'))

    op.drop_table('media_items')
    with op.batch_alter_table('media_collection_localizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_collection_localizations_locale'))
        batch_op.drop_index(batch_op.f('ix_media_collection_localizations_collection_id'))

    op.drop_table('media_collection_localizations')
    with op.batch_alter_table('external_studio_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_studio_links_studio_id'))
        batch_op.drop_index(batch_op.f('ix_external_studio_links_provider'))
        batch_op.drop_index(batch_op.f('ix_external_studio_links_external_id'))

    op.drop_table('external_studio_links')
    with op.batch_alter_table('external_source_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_source_links_provider'))
        batch_op.drop_index(batch_op.f('ix_external_source_links_person_id'))
        batch_op.drop_index(batch_op.f('ix_external_source_links_external_id'))

    op.drop_table('external_source_links')
    with op.batch_alter_table('external_collection_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_collection_links_provider'))
        batch_op.drop_index(batch_op.f('ix_external_collection_links_external_id'))
        batch_op.drop_index(batch_op.f('ix_external_collection_links_collection_id'))

    op.drop_table('external_collection_links')
    with op.batch_alter_table('custom_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_custom_lists_name'))
        batch_op.drop_index(batch_op.f('ix_custom_lists_list_type'))

    op.drop_table('custom_lists')
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_background_tasks_name'))

    op.drop_table('background_tasks')
    with op.batch_alter_table('action_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_batches_user_id'))

    op.drop_table('action_batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_is_adult'))

    op.drop_table('tags')
    op.drop_table('system_settings')
    with op.batch_alter_table('studios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studios_parent_studio_id'))
        batch_op.drop_index(batch_op.f('ix_studios_name'))

    op.drop_table('studios')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_orientation'))
        batch_op.drop_index(batch_op.f('ix_people_name'))
        batch_op.drop_index(batch_op.f('ix_people_known_for_department'))
        batch_op.drop_index(batch_op.f('ix_people_is_adult'))
        batch_op.drop_index(batch_op.f('ix_people_is_active'))
        batch_op.drop_index(batch_op.f('ix_people_height'))
        batch_op.drop_index(batch_op.f('ix_people_hair_color'))
        batch_op.drop_index(batch_op.f('ix_people_ethnicity'))
        batch_op.drop_index(batch_op.f('ix_people_cup_size'))

    op.drop_table('people')
    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_collections_provider'))
        batch_op.drop_index(batch_op.f('ix_media_collections_external_id'))

    op.drop_table('media_collections')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_is_adult'))

    op.drop_table('libraries')
    # ### end Alembic commands ###
