"""add_person_career_columns

Revision ID: 6667dd46e2ec
Revises: aa6247f8253c
Create Date: 2026-06-25 12:17:38.606356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6667dd46e2ec'
down_revision: Union[str, Sequence[str], None] = 'aa6247f8253c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_start_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_end_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('career_end_year')
        batch_op.drop_column('career_start_year')

    # ### end Alembic commands ###
