"""add_metadata_indexes

Revision ID: 6cc1f8926f62
Revises: ba8eae085467
Create Date: 2026-06-21 21:04:48.472768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc1f8926f62'
down_revision: Union[str, Sequence[str], None] = 'ba8eae085467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_list_items_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_list_id'), ['list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custom_list_items_studio_id'), ['studio_id'], unique=False)

    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_relations_child_match_id'), ['child_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_parent_match_id'), ['parent_match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_relations_relation_type'), ['relation_type'], unique=False)

    with op.batch_alter_table('external_match_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_match_links_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_match_links_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_match_links_provider'), ['provider'], unique=False)

    with op.batch_alter_table('media_person_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_person_links_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_person_links_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_person_links_role'), ['role'], unique=False)

    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_localizations_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_localizations_match_id'), ['match_id'], unique=False)

    with op.batch_alter_table('metadata_match_studios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metadata_match_studios_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_metadata_match_studios_studio_id'), ['studio_id'], unique=False)


    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_overrides_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_favorite_at'), ['is_favorite_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_tracked'), ['is_tracked'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_is_watched'), ['is_watched'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_last_watched_at'), ['last_watched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_comment_at'), ['user_comment_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_user_rating_at'), ['user_rating_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_overrides_watch_count'), ['watch_count'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_overrides_watch_count'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_rating_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_user_comment_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_last_watched_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_watched'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_tracked'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_favorite_at'))
        batch_op.drop_index(batch_op.f('ix_user_overrides_is_favorite'))


    with op.batch_alter_table('metadata_match_studios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_match_studios_studio_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_match_studios_relation_type'))

    with op.batch_alter_table('metadata_localizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_localizations_match_id'))
        batch_op.drop_index(batch_op.f('ix_metadata_localizations_locale'))

    with op.batch_alter_table('media_person_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_person_links_role'))
        batch_op.drop_index(batch_op.f('ix_media_person_links_person_id'))
        batch_op.drop_index(batch_op.f('ix_media_person_links_match_id'))

    with op.batch_alter_table('external_match_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_match_links_provider'))
        batch_op.drop_index(batch_op.f('ix_external_match_links_match_id'))
        batch_op.drop_index(batch_op.f('ix_external_match_links_external_id'))

    with op.batch_alter_table('entity_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_parent_match_id'))
        batch_op.drop_index(batch_op.f('ix_entity_relations_child_match_id'))

    with op.batch_alter_table('custom_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_list_items_studio_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_person_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_order'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_match_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_list_id'))
        batch_op.drop_index(batch_op.f('ix_custom_list_items_collection_id'))

    # ### end Alembic commands ###
