"""add is_active to metadata_matches

Revision ID: 851f9ea1a4e2
Revises: 6cc1f8926f62
Create Date: 2026-06-21 21:27:34.336227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f9ea1a4e2'
down_revision: Union[str, Sequence[str], None] = '6cc1f8926f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.sql.true()))
        batch_op.create_index(batch_op.f('ix_metadata_matches_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadata_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metadata_matches_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
