"""add_snapshot_path_to_playback_peak_logs

Revision ID: 9f1bf7f9dc2b
Revises: ecb02b5bc67f
Create Date: 2026-07-06 22:24:45.026369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1bf7f9dc2b'
down_revision: Union[str, Sequence[str], None] = 'ecb02b5bc67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_peak_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playback_peak_logs', schema=None) as batch_op:
        batch_op.drop_column('snapshot_path')

    # ### end Alembic commands ###
