"""add_local_backdrop_path_to_collection

Revision ID: aa6247f8253c
Revises: d640607ac55c
Create Date: 2026-06-25 08:37:08.342711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6247f8253c'
down_revision: Union[str, Sequence[str], None] = 'd640607ac55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_backdrop_path', sa.String(), nullable=True))

    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.alter_column('user_rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.alter_column('user_rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.drop_column('local_backdrop_path')

    # ### end Alembic commands ###
