"""move_physical_overrides_to_media_item

Revision ID: d640607ac55c
Revises: c1d9f4e7b2aa
Create Date: 2026-06-24 08:34:29.424956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd640607ac55c'
down_revision: Union[str, Sequence[str], None] = 'c1d9f4e7b2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_edition', sa.Enum('NONE', 'THEATRICAL', 'DIRECTORS_CUT', 'EXTENDED', 'UNRATED', 'REMASTERED', 'SPECIAL', 'ULTIMATE', 'COLLECTORS_EDITION', 'FAN_EDIT', name='movieedition'), nullable=True))
        batch_op.add_column(sa.Column('custom_audio_type', sa.Enum('NONE', 'MONO', 'STEREO', 'SURROUND', 'DUAL_AUDIO', 'MULTI_AUDIO', name='mediaaudiotype'), nullable=True))
        batch_op.add_column(sa.Column('custom_source', sa.Enum('NONE', 'BLURAY', 'WEB', 'DVD', 'TV', 'CAM', name='mediasource'), nullable=True))
        batch_op.create_index(batch_op.f('ix_media_items_custom_audio_type'), ['custom_audio_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_custom_edition'), ['custom_edition'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_custom_source'), ['custom_source'], unique=False)

    # Data migration: copy physical custom fields from user_overrides to media_items
    op.execute("""
        UPDATE media_items
        SET custom_edition = (
            SELECT u.custom_edition FROM user_overrides u
            WHERE u.media_item_id = media_items.id AND u.custom_edition IS NOT NULL LIMIT 1
        ),
        custom_audio_type = (
            SELECT u.custom_audio_type FROM user_overrides u
            WHERE u.media_item_id = media_items.id AND u.custom_audio_type IS NOT NULL LIMIT 1
        ),
        custom_source = (
            SELECT u.custom_source FROM user_overrides u
            WHERE u.media_item_id = media_items.id AND u.custom_source IS NOT NULL LIMIT 1
        )
        WHERE EXISTS (
            SELECT 1 FROM user_overrides u
            WHERE u.media_item_id = media_items.id AND (u.custom_edition IS NOT NULL OR u.custom_audio_type IS NOT NULL OR u.custom_source IS NOT NULL)
        );
    """)

    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.drop_column('custom_audio_type')
        batch_op.drop_column('custom_source')
        batch_op.drop_column('custom_edition')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_edition', sa.VARCHAR(length=18), nullable=True))
        batch_op.add_column(sa.Column('custom_source', sa.VARCHAR(length=6), nullable=True))
        batch_op.add_column(sa.Column('custom_audio_type', sa.VARCHAR(length=11), nullable=True))

    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_custom_source'))
        batch_op.drop_index(batch_op.f('ix_media_items_custom_edition'))
        batch_op.drop_index(batch_op.f('ix_media_items_custom_audio_type'))
        batch_op.drop_column('custom_source')
        batch_op.drop_column('custom_audio_type')
        batch_op.drop_column('custom_edition')

    # ### end Alembic commands ###
