"""add_collection_parts_count

Revision ID: def3498e635a
Revises: 9f1bf7f9dc2b
Create Date: 2026-07-19 22:33:37.358828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def3498e635a'
down_revision: Union[str, Sequence[str], None] = '9f1bf7f9dc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parts_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_collections', schema=None) as batch_op:
        batch_op.drop_column('parts_count')

    # ### end Alembic commands ###
