"""Add custom_language override

Revision ID: e40cfdda063f
Revises: 6262c9c39e90
Create Date: 2026-06-20 19:49:02.640483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40cfdda063f'
down_revision: Union[str, Sequence[str], None] = '6262c9c39e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_overrides', schema=None) as batch_op:
        batch_op.drop_column('custom_language')

    # ### end Alembic commands ###
