import { getTabDefinition, getVisibleOrganizationTabs } from '../settingsTabs.config.jsx';

export default function useSettingsRenderContext({
  t,
  form,
  setForm,
  isSaving,
  isWiping,
  isScanActive,
  isBackgroundActive,
  isSyncActive,
  validationErrors,
  formInputs,
  insertTag,
  handleChange,
  handleCheckboxChange,
  handlePickFolder,
  handlePickFile,
  handleExportSettings,
  handleImportClick,
  handleImportSettings,
  handleWipeDatabase,
  isWipingCache,
  handleWipeCache,
  activeTab,
  optionContext,
}) {
  const renderContext = {
    t,
    form,
    setForm,
    isSaving,
    isWiping,
    isWipingCache,
    isScanActive,
    isBackgroundActive: false,
    realBackgroundActive: isBackgroundActive,
    isSyncActive,
    validationErrors,
    formInputs,
    insertTag,
    handleChange,
    handleCheckboxChange,
    handlePickFolder,
    handlePickFile,
    handleExportSettings,
    handleImportClick,
    handleImportSettings,
    handleWipeDatabase,
    handleWipeCache,
    activeTab,
    ...optionContext,
  };

  return {
    renderContext,
    visibleOrganizationTabs: getVisibleOrganizationTabs(renderContext),
    activeTabDefinition: getTabDefinition(activeTab),
    formContextActions: {
      handleChange,
      handleCheckboxChange,
      handlePickFolder,
      handlePickFile,
      insertTag,
    },
  };
}
