# Import all schemas from domain layer to maintain backward compatibility
from app.domains.users.schemas import (
    BaseSchema as BaseSchema,
    UserCreate as UserCreate,
    UserRead as UserRead,
    UserOverrideCreate as UserOverrideCreate,
    UserOverrideRead as UserOverrideRead,
    CustomListCreate as CustomListCreate,
    CustomListItemRead as CustomListItemRead,
    CustomListRead as CustomListRead,
    ItemOverridesUpdate as ItemOverridesUpdate,
    ItemStatusUpdate as ItemStatusUpdate,
    ImageOverrideUpdate as ImageOverrideUpdate,
    BulkOverridesUpdate as BulkOverridesUpdate,
    BulkTagsUpdate as BulkTagsUpdate,
    BulkWatchedUpdate as BulkWatchedUpdate,
    CustomTagImage as CustomTagImage,
    TagResponse as TagResponse,
    CustomListItemResponse as CustomListItemResponse,
    CustomListResponse as CustomListResponse,
    CustomListDetailResponse as CustomListDetailResponse,
    ListMembershipResponse as ListMembershipResponse,
    CatalogItemResponse as CatalogItemResponse,
    CatalogPageResponse as CatalogPageResponse,
    CatalogResponse as CatalogResponse,
    BulkUpdateResponse as BulkUpdateResponse,
)
